### ISSUE TITLE
Error in uploadFile function

### ISSUE THREAD

**Issue by OscarDaSilva** [f2face/cloudflare-r2#2]
Hi,

I'm getting error "An error was encountered in a non-retryable streaming request." when uploading file from path. I think an "await" is missing on this line.

https://github.com/f2face/cloudflare-r2/blob/e8e4de774db1eef680823c619d2542a59fe05ab3/src/Bucket.ts#L262

Thanks.

**Comment by f2face** [comment]
You're right. Fixing this right now.
