### ISSUE TITLE
publicUrls missing

### ISSUE THREAD

**Issue by mateie** [f2face/cloudflare-r2#3]
I enabled r2 subdomain publlc access but both `publicUrl` and `publicUrls` are empty. Is this a caching issue? How can this be fixed?

![image](https://github.com/f2face/cloudflare-r2/assets/48449640/a9996f6c-15d4-4c80-90e2-ffc706aec0e5)

**Comment by f2face** [comment]
You need to add this line so the library knows your public URLs:
```
bucket.provideBucketPublicUrl([
    'https://<your-r2-subdomain>',
    'https://<your-other-custom-domain>'
]);
```

**Comment by f2face** [comment]
Feel free to reopen the issue if you still encounter this problem.
