### ISSUE TITLE
Issue with deleteObject

### ISSUE THREAD

**Issue by vwh** [f2face/cloudflare-r2#5]
Thank you for your work.

A problem with `deleteObject`
if it successes or not it always return false

https://github.com/f2face/cloudflare-r2/blob/main/src/Bucket.ts#L376
It never return 200 stats code 
```ts
return result.$metadata.httpStatusCode === 200;
```

**Comment by f2face** [comment]
I see. The returned status code is always 204, regardless of whether the object existed or not.
Fixing this in a minute.
